config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users
  
  resources :photos do
    resources :comments
    resources :likes
  end

  root 'photos#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :photo
end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :photo, :counter_cache => true
  	belongs_to :user
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_many :comments
  belongs_to :creator, :class_name => "User", :foreign_key => "user_id"

  has_many :likes
  has_many :like_users, :through => :likes, :source => "user"

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def find_like_by_user(user)
    user && self.likes.where( :user_id => user.id ).last
  end

  # def can_edit_by_user?(user)  
  # 	user && ( self.user == user || user.is_admin? )
  # end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :photos
  devise :omniauthable, :omniauth_providers => [:facebook]

  def is_admin?
  	self.role == "admin"
  end

  def self.from_omniauth(auth)
	  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	    user.email = auth.info.email
	    user.password = Devise.friendly_token[0,20]
	    user.username = auth.info.name   # assuming the user model has a name
	    user.fb_image = auth.info.image # assuming the user model has an image
	    user.fb_uid = auth.info.fb_uid # assuming the user model has an uid
	  end
	end
	def self.new_with_session(params, session)
		super.tap do |user|
		  if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
		    user.email = data["email"] if user.email.blank?
		    user.fb_image = data["image"] if user.fb_image.blank?
		  end
		end
	end

	has_many :my_photos, :class_name => "Photo"
  	has_many :likes
  	has_many :like_photos, :through => :likes, :source => "photo"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :authenticate_user!

	def create
    @photo = Photo.find( params[:photo_id] )
    @comment = @photo.comments.build( comment_params )
    @comment.user = current_user

    @comment.save!

    redirect_to root_url
 	end
 
  	protected

  	def comment_params
    params.require(:comment).permit(:content)
  	end
	
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :authenticate_user!
  
	  def create
    @photo = Photo.find( params[:photo_id] )

    existing_like = @photo.find_like_by_user(current_user)
    unless existing_like
      @like = Like.create( :user => current_user, :photo => @photo)
    end

    respond_to do |format|
      format.html { redirect_to :back }
      format.js {
        @photo.reload
        render :template => "likes/reload"
      }
    end
  end

  def destroy
    @photo = Photo.find( params[:photo_id] )
    @like = current_user.likes.find( params[:id] )
    @like.destroy
    @like = nil

    respond_to do |format|
      format.html { redirect_to :back }
      format.js {
        @photo.reload
        render :template => "likes/reload"
      }
    end
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  
  before_action :authenticate_user!, :except => [:index]

  def index
    @photos = Photo.page(params[:page])
    @photo = Photo.new
  end
  # add to pop up
  # def new
  #  @photo = Photo.new
  # end

  def create
    @photo = Photo.new( photo_params )
    
    @photo.creator = current_user

    if @photo.save
      redirect_to root_url
    else
      render :action => :new
    end
  end

  protected

  def photo_params
    params.require(:photo).permit(:content, :image)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
	def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>SocialAlbum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="main">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Brand</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
          <li><%=image_tag current_user.fb_image %></li>
          <%end %>
            <li><a href="#"><span class="glyphicon glyphicon-home" aria-hidden="true"></span></a></li>
            <% if current_user %>
              <%= current_user.username %>

              <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
              <%= link_to('修改密碼', edit_registration_path(:user)) %>

            <% else %>
              <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
            <% end %>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  </div> 
  <div id="main-container" class="container">
      <div class="row">

        <div id="content" class="col-xs-12">

        <% if flash[:notice] %>
          <div class="alert alert-success"><%= flash[:notice] %></div>
        <% end %>

        <% if flash[:alert] %>
          <div class="alert alert-warning"><%= flash[:alert] %></div>
        <% end %>
      </div>
    </div>
 </div>
</div> <!-- /.main -->
  <%= yield %> 
</body>
</html>

app/views/likes/_show.html.erb
Likes: <%= photo.likes_count %>

<% photo.like_users.each do |u| %>
  <%= link_to u.username, user_path(u) %>
<% end %>

<% if like %>
  <%= link_to "-1", photo_like_path(photo, like), :method => :delete, :remote => true %>
<% else %>
 <%= link_to "+1", photo_likes_path(photo), :method => :post, :remote => true %>
<% end %> 

app/views/likes/reload.js.erb
$("#photo-like-<%= @photo.id %>").html("<%= j(render :partial => "show", :locals => { :photo => @photo, :like => @like } ) %>");

app/views/photos/index.html.erb
  <div class="container text-center" >
      <p>
		<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">			<%= "Upload Photo"%>
		</button>
      </p>

  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog text-left">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">New Photo</h4>
        </div>
        <div class="modal-body">
  		<%= form_for @photo, :url => photos_path do |f| %>

  		  <p>
  		    <%= f.label :content %>
  		   </p>
  		    <%= f.text_area(:content, size: '50x10') %>
  		  <p>
  		    <%= f.label :image %>
  		    <%= f.file_field :image %>
  		  </p>
  		
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.submit class: "btn btn-info" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

    <% @photos.each do |photo| %>

      <%= link_to image_tag(photo.image.url(:medium)),photo.image.url, :target => "_blank"  %>
      
      <p><%= photo.content %></p>

			
		  <% like = photo.find_like_by_user(current_user) %>

      <div id="photo-like-<%= photo.id %>">
      <%= render :partial => "likes/show", :locals => { :photo => photo, :like => like } %>
      </div>

<!--         <%#if photo.can_edit_by_user?(current_user) %>
          Delete Photo
        <%#end %> -->
      <hr>
    <% end %>
  </div>
</div>
 

app/views/photos/new.html.erb
<h2>New photo</h2>

<%= form_for @photo, :url => photos_path do |f| %>

  <p>
    <%= f.label :content %>
    <%= f.text_field :content , :rows => "10"  %>
  </p>

  <p>
    <%= f.label :image %>
    <%= f.file_field :image %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/show.html.erb
<h1>hi,<%= @user.username %></h1>